name: DSE Daily Automation

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7 AM UTC (~10 AM Tanzania time)
  workflow_dispatch:     # Allows manual run

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install gspread google-auth pandas matplotlib scikit-learn requests google-api-python-client

    - name: Create service account JSON
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > service_account.json

    - name: Run DSE analysis script
      run: |
        python dse_bot.py
